
[SupersonicTheme]
Name = "Catppuccin Macchiato (Blue)"
Version = "0.2"
SupportsDark = true
SupportsLight = true


[LightColors]
PageBackground = "#EFF1F5FF"
ListHeader = "#DCE0E8FF"
PageHeader = "#E6E9EFFF"
Background = "#DCE0E8FF"
Button = "#E6E9EFFF"
DisabledButton = "#CCD0DAFF"
Disabled = "#4C4F69FF"
Error = "#D20F39FF"
Focus = "#C5D5F5FF"
Foreground = "#4C4F69FF"
ForegroundOnError = "#EFF1F5FF"
ForegroundOnPrimary = "#EFF1F5FF"
ForegroundOnSuccess = "#EFF1F5FF"
ForegroundOnWarning = "#EFF1F5FF"
HeaderBackground = "#CCD0DAFF"
Hover = "#DBE3F5FF"
Hyperlink = "#1E66F5FF"
InputBackground = "#E6E9EFFF"
InputBorder = "#CCD0DAFF"
MenuBackground = "#E6E9EFFF"
OverlayBackground = "#E6E9EFFF"
Placeholder = "#7C7F93FF"
Pressed = "#CCD0DA66"
Primary = "#1E66F5FF"
ScrollBar = "#E6E9EF99"
Selection = "#BBCFF5FF"
Separator = "#DCE0E8FF"
Success = "#40A02BFF"
Warning = "#DF8E1DFF"


[DarkColors]
PageBackground = "#24273AFF"
ListHeader = "#181926FF"
PageHeader = "#1E2030FF"
Background = "#181926FF"
Button = "#1E2030FF"
DisabledButton = "#363A4FFF"
Disabled = "#CAD3F5FF"
Error = "#ED8796FF"
Focus = "#39425FFF"
Foreground = "#CAD3F5FF"
ForegroundOnError = "#24273AFF"
ForegroundOnPrimary = "#24273AFF"
ForegroundOnSuccess = "#24273AFF"
ForegroundOnWarning = "#24273AFF"
HeaderBackground = "#363A4FFF"
Hover = "#2E344CFF"
Hyperlink = "#8AADF4FF"
InputBackground = "#1E2030FF"
InputBorder = "#363A4FFF"
MenuBackground = "#1E2030FF"
OverlayBackground = "#1E2030FF"
Placeholder = "#939AB7FF"
Pressed = "#363A4F66"
Primary = "#8AADF4FF"
ScrollBar = "#1E203099"
Selection = "#3E4868FF"
Separator = "#181926FF"
Success = "#A6DA95FF"
Warning = "#EED49FFF"